name: Build

on:
  push:

  pull_request:




permissions:
  contents: read






jobs:

  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-2022, ubuntu-22.04, macos-12 ]
        config: [ Release, Debug ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - run: cmake -B build -D BUILD_SHARED_LIBS=true -D CMAKE_BUILD_TYPE=${{ matrix.config }}
    - run: cmake --build build --config ${{ matrix.config }}
    - uses: actions/upload-artifact@v3.1.2
      with:
        name: ${{ matrix.os }}_${{ matrix.config }}
        path: build/${{ matrix.config }}
        if-no-files-found: error

  vendor_package:
    needs:
      - build
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/download-artifact@v3.0.2
      with:
        path: freetype
    - uses: actions/upload-artifact@v3.1.2
      with:
        name: freetype_vendor_package_all_builds
        path: freetype
        if-no-files-found: error

